version: '3.8'

networks:
  vita:
    driver: bridge

services:
  nginx:
    image: nginx:1.25
    ports:
      - "1243:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_healthy
    networks:
      - vita

  php:
    image: php:7.4-fpm
    volumes:
      - .:/var/local/sandboxes/dev/www
    environment:
      - PHP_FPM_LISTEN=0.0.0.0:9000
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - vita

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vita

volumes:
  postgres_data:
